--- kohya: sd-scripts LoRA training target.
-- Generates TOML config and dataset directory structure
-- compatible with kohya-ss/sd-scripts SDXL LoRA training.
--
-- Impl module: HOW to train using kohya sd-scripts.
--
-- Includes env_spec: tested package combinations for reproducible
-- Pod setup (1-command via setup_script).

local env_mod = require("vdsl.training.env")
local base    = require("vdsl.training.methods.sdscripts_base")

local M = {}

-- ============================================================
-- Environment specification (known-good for RTX 4090 + torch 2.6)
-- ============================================================

M.env = env_mod.base_sdxl_cu124:merge(env_mod.new {
  name = "kohya",
  pip = {
    install = {
      { "bitsandbytes" },
      { "lion-pytorch" },
      { "prodigyopt" },
      { "imagesize" },
      { "toml" },
      { "voluptuous" },
    },
  },
  repos = {
    {
      url = "https://github.com/kohya-ss/sd-scripts.git",
      dir = "/workspace/sd-scripts",
    },
  },
  post_cmds = {
    "cd /workspace/sd-scripts && pip install -e . --quiet",
    "mkdir -p /workspace/models /workspace/datasets",
  },
  verify = { "bitsandbytes" },
  notes = {
    "sd-scripts: pip install -e . (latest removes [torch] extra, library 0.0.0 warning is harmless)",
    "imagesize/toml/voluptuous: sd-scripts runtime deps not resolved by pip install -e .",
    "python → python3 on RunPod (no python symlink)",
    "bitsandbytes needed for AdamW8bit optimizer",
    "prodigyopt needed for Prodigy optimizer (popular alternative)",
  },
})

--- Generate kohya sd-scripts TOML config.
-- @param opts table (see sdscripts_base.resolve for common params)
-- @return string TOML config text
function M.config(opts)
  return base.config(opts, "LoRA Training Config — generated by VDSL training\n# Target: SDXL / Illustrious / NoobAI", function(p)
    return string.format(
[[[network]
network_module = "networks.lora"
network_dim = %d
network_alpha = %d
network_train_unet_only = true]],
      p.rank, p.alpha
    )
  end)
end

--- Build kohya-compatible dataset directory path.
-- @param opts table { data_dir, trigger, repeats? }
-- @return string path like "/workspace/datasets/10_abc01"
function M.dataset_path(opts)
  local repeats = opts.repeats or 10
  return string.format("%s/%d_%s", opts.data_dir, repeats, opts.trigger)
end

--- Generate the training execution command.
-- @param opts table { config_path, repo_dir? }
-- @return string shell command
function M.command(opts)
  return base.command(opts)
end

return M
