--- leco: Low-rank Editing of Concept (LECO) training target.
-- Text-only concept editing — no training images required.
-- Learns the difference between two text prompts as a LoRA.
--
-- Impl module: HOW to train LECO LoRAs.

local Entity = require("vdsl.entity")

local M = {}

--- Extract the text prompt from a concept axis side.
-- Supports both { prompt = "text" } and { subject = Subject } forms.
-- @param archetype table concept archetype
-- @param side string "before" or "after"
-- @return string prompt text
function M.axis_prompt(archetype, side)
  if not archetype or archetype.kind ~= "concept" then
    error("leco.axis_prompt: concept archetype required", 2)
  end
  local axis_side = archetype.axis[side]
  if not axis_side then
    error("leco.axis_prompt: no '" .. side .. "' in axis", 2)
  end
  if axis_side.prompt then
    return axis_side.prompt
  end
  if axis_side.subject then
    return Entity.resolve_text(axis_side.subject)
  end
  return ""
end

--- Generate LECO YAML config.
-- @param opts table {
--   archetype    table    concept archetype
--   checkpoint   string   pretrained model path
--   rank?        number   LoRA rank (default 4)
--   alpha?       number   LoRA alpha (default 1.0)
--   iterations?  number   training iterations (default 500)
--   lr?          number   learning rate (default 0.0001)
--   method?      string   training method (default "noxattn")
-- }
-- @return string YAML config text
function M.config(opts)
  if not opts.checkpoint then
    error("leco.config: 'checkpoint' is required", 2)
  end
  if not opts.archetype or opts.archetype.kind ~= "concept" then
    error("leco.config: concept archetype is required", 2)
  end

  local name       = opts.archetype.name
  local rank       = opts.rank or 4
  local alpha      = opts.alpha or 1.0
  local iterations = opts.iterations or 500
  local lr         = opts.lr or 0.0001
  local method     = opts.method or "noxattn"

  local before_prompt = M.axis_prompt(opts.archetype, "before")
  local after_prompt  = M.axis_prompt(opts.archetype, "after")

  return string.format(
[[# LECO Config — generated by VDSL training
# Method: Low-rank Editing of Concept (text-only)

name: "%s"
pretrained_model_name_or_path: "%s"
rank: %d
alpha: %g
iterations: %d
lr: %g
training_method: "%s"

# Concept axis (text-only, no images)
target:
  positive: "%s"
  unconditional: "%s"
]],
    name, opts.checkpoint,
    rank, alpha,
    iterations, lr,
    method,
    after_prompt, before_prompt
  )
end

--- Generate the training execution command.
-- @param opts table { config_path, repo_dir?, venv? }
-- @return string shell command
function M.command(opts)
  if not opts.config_path then
    error("leco.command: 'config_path' is required", 2)
  end
  local python = "python"
  if opts.venv then
    python = opts.venv .. "/bin/python"
  end
  local repo = opts.repo_dir or "/workspace/leco"

  return string.format(
    "cd %s && %s train_leco.py --config_file %s",
    repo, python, opts.config_path
  )
end

return M
