--- lycoriss: LyCORIS (LoHA / LoKr / LoCon) training target.
-- Extends kohya sd-scripts with LyCORIS network modules.
-- Same dataset structure as kohya, different network_module in config.
--
-- Impl module: HOW to train LyCORIS LoRAs.
--
-- Includes env_spec: kohya base + lycoris-lora pip package.

local env_mod = require("vdsl.training.env")
local kohya   = require("vdsl.training.methods.kohya")
local base    = require("vdsl.training.methods.sdscripts_base")

local M = {}

-- ============================================================
-- Environment specification (kohya base + lycoris-lora)
-- ============================================================

M.env = kohya.env:merge(env_mod.new {
  name = "lycoriss",
  pip = {
    install = {
      { "lycoris-lora" },
    },
  },
  verify = { "lycoris" },
  notes = {
    "lycoris-lora pip package provides lycoris.kohya network module",
    "network_args format: algo=loha, conv_dim=N, conv_alpha=N",
  },
})

local ALGOS = {
  loha  = true,
  lokr  = true,
  locon = true,
  full  = true,
}

--- Generate LyCORIS TOML config (kohya-compatible with lycoris network).
-- @param opts table (see sdscripts_base.resolve for common params)
--   algo?       string   LyCORIS algorithm (default "loha")
--   conv_rank?  number   convolution rank for locon/loha (default rank)
--   conv_alpha? number   convolution alpha (default conv_rank/2)
-- @return string TOML config text
function M.config(opts)
  local algo = opts.algo or "loha"
  if not ALGOS[algo] then
    error("lycoriss.config: unknown algo '" .. algo
      .. "' (available: loha, lokr, locon, full)", 2)
  end

  return base.config(opts, "LyCORIS Training Config — generated by VDSL training\n# Algorithm: " .. algo, function(p)
    local conv_rank  = opts.conv_rank or p.rank
    local conv_alpha = opts.conv_alpha or math.floor(conv_rank / 2)
    return string.format(
[=[[network]
network_module = "lycoris.kohya"
network_dim = %d
network_alpha = %d
network_train_unet_only = true
network_args = ["algo=%s", "conv_dim=%d", "conv_alpha=%d"]]=],
      p.rank, p.alpha, algo, conv_rank, conv_alpha
    )
  end)
end

--- Generate the training execution command.
-- Same as kohya (uses sd-scripts with LyCORIS installed).
-- @param opts table { config_path, repo_dir? }
-- @return string shell command
function M.command(opts)
  return base.command(opts)
end

return M
