--- ti: Textual Inversion (Embedding) training target.
-- Learns a new token embedding instead of a LoRA weight delta.
-- Uses kohya sd-scripts train_textual_inversion.py.
--
-- Impl module: HOW to train Textual Inversion embeddings.
--
-- Note: ti shares the sd-scripts ecosystem but its TOML structure differs
-- enough from kohya/lycoriss (no bucket_no_upscale, no save_precision,
-- no cache_text_encoder_outputs, no sdpa, different defaults) that using
-- sdscripts_base.config() would require more overrides than it saves.
-- We use base.resolve() for parameter resolution and base.command() for
-- the execution command, keeping the TOML template self-contained.

local base = require("vdsl.training.methods.sdscripts_base")

local M = {}

-- TI-specific defaults differ from the LoRA family
local TI_DEFAULTS = {
  steps     = 2000,
  lr        = 0.005,
  optimizer = "AdamW",
}

--- Generate Textual Inversion TOML config.
-- @param opts table (see sdscripts_base.resolve for common params)
--   token?       string   trigger token (default archetype.trigger)
--   init_word?   string   initialization word (default "girl")
--   num_vectors? number   vectors per token (default 8)
-- @return string TOML config text
function M.config(opts)
  -- Apply TI-specific defaults before base resolution
  local merged = {}
  for k, v in pairs(opts) do merged[k] = v end
  for k, v in pairs(TI_DEFAULTS) do
    if merged[k] == nil then merged[k] = v end
  end

  local p = base.resolve(merged)

  local token       = opts.token or p.trigger
  local init_word   = opts.init_word or "girl"
  local num_vectors = opts.num_vectors or 8

  return string.format(
[[# Textual Inversion Config — generated by VDSL training
# Output: embedding .safetensors

[general]
enable_bucket = true

[model]
pretrained_model_name_or_path = "%s"

[dataset]
train_data_dir = "%s"
resolution = "%d,%d"
caption_extension = ".txt"

[embedding]
token_string = "%s"
init_word = "%s"
num_vectors_per_token = %d

[optimizer]
optimizer_type = "%s"
learning_rate = %g
lr_scheduler = "%s"

[training]
output_dir = "%s"
output_name = "%s"
save_model_as = "safetensors"
max_train_steps = %d
train_batch_size = 1
mixed_precision = "%s"
gradient_checkpointing = true
cache_latents = true
seed = 42
]],
    p.checkpoint, p.data_dir, p.resolution, p.resolution,
    token, init_word, num_vectors,
    p.optimizer, p.lr, p.scheduler,
    p.output_dir, token, p.steps, p.precision
  )
end

--- Generate the training execution command.
-- @param opts table { config_path, repo_dir? }
-- @return string shell command
function M.command(opts)
  return base.command {
    config_path = opts.config_path,
    repo_dir    = opts.repo_dir,
    script      = "sdxl_train_textual_inversion.py",
  }
end

return M
